security:
    # https://symfony.com/doc/current/security.html#registering-the-user-hashing-passwords
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'

    # https://symfony.com/doc/current/security.html#loading-the-user-the-user-provider
    providers:
        # used to reload user from session & read persistence for light weight user objects
        app_user_provider:
            entity: # Busca en la entidad 'User' y usa el campo 'email' para buscar usuarios
                class: App\Entity\User 
                property: email
    firewalls:
        dev:
            # Ensure dev tools and static assets are always allowed
            pattern: ^/(_profiler|_wdt|assets|build)/
            security: false
        main:
            lazy: true # Carga el usuario solo cuando es necesario
            provider: app_user_provider # Para buscar usuarios use la configuracion de providers de arriba
            
            # Login tradicional con formulario
            form_login:
                login_path: app_login # Ruta del formulario de login
                check_path: app_login # Ruta que verifica el login
                enable_csrf: true # Habilita el CSRF (Cross-Site Request Forgery)
                
                # A donde va el usuario despues de iniciar sesion (cuando el login sea correcto, lo mandamos al frontend de React)
                default_target_path: '%frontend_url%' # Ruta a la que va el usuario despues de iniciar sesion (redirige a frontend_url dentro de services.yaml)
                                                      # cuando era :5173 el problema era que nos redirigia a una página que no existia si cambiabamos de puerto
                
                always_use_default_target_path: true # Redirige siempre a React después de iniciar sesión
            
            # Login con JSON (para peticiones AJAX con las que enviamos el email y la contraseña en formato JSON)
            json_login:
                check_path: app_login
            
            # Logout (cerrar sesión)
            logout:
                path: app_logout
                target: logout_success # Redirige a la ruta interna que nos envía a React



    # Note: Only the *first* matching rule is applied
    access_control:
        # - { path: ^/admin, roles: ROLE_ADMIN }
        # - { path: ^/profile, roles: ROLE_USER }

when@test:
    security:
        password_hashers:
            # Password hashers are resource-intensive by design to ensure security.
            # In tests, it's safe to reduce their cost to improve performance.
            Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
                algorithm: auto
                cost: 4 # Lowest possible value for bcrypt
                time_cost: 3 # Lowest possible value for argon
                memory_cost: 10 # Lowest possible value for argon
